#!/bin/bash

set -e

perl="$1"
dc="dc-$perl"
opts="--force -j 3 --noman --notest"

if [ ! -e "$PERLBREW_ROOT/perls/$dc" ]; then
    echo building perl version $dc
    perlbrew install $perl $opts          --as "$dc"
fi

if [ ! -e "$PERLBREW_ROOT/perls/$dc-thr" ]; then
    echo building perl version $dc-thr
    perlbrew install $perl $opts --thread --as "$dc-thr"
fi

echo perl version $dc built
