#!/usr/bin/perl

use strict;
use warnings;

my $root = $ARGV[0] // $ENV{PERLBREW_ROOT} // die "No root";

for my $d (<$root/perls/*>)
{
    my $p = $d =~ s|.*/||r;
    print "linking $p\n";
    my $n = "/usr/local/bin/$p";
    unlink $n;
    my $perl = "$d/bin/perl";
    symlink $perl, $n or die "Can't ln $perl => $n: $!";
}
